[nosetests]
verbosity=2
with-coverage=1
cover-erase=1
cover-package=server
cover-html=1
cover-html-dir=cover

[flake8]
max-line-length=120
exclude=.git,__pycache__,venv

[pylint]
max-line-length=120
good-names=i,j,k,ex,Run,_,id